name: halyagosi_horgaszto
description: Halyagosi Horgaszto - To Dashboard
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
flutter:
  uses-material-design: true
