name: Build Halyagosi IPA
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
      - name: Detect project folder
        run: |
          ls -la
          ls -la halyagosi-main || true
          ls -la halyagosi-main/halyagosi-main || true
          if [ -f "halyagosi-main/halyagosi-main/pubspec.yaml" ]; then
            echo "PROJECT_DIR=halyagosi-main/halyagosi-main" >> $GITHUB_ENV
          elif [ -f "halyagosi-main/pubspec.yaml" ]; then
            echo "PROJECT_DIR=halyagosi-main" >> $GITHUB_ENV
          else
            echo "PROJECT_DIR=." >> $GITHUB_ENV
          fi
          echo "Using PROJECT_DIR"
          cat $GITHUB_ENV
      - name: Build
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub get
          flutter build ios --no-codesign --release
      - name: Make IPA
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          mkdir Payload
          cp -R build/ios/iphoneos/Runner.app Payload/
          zip -r Halyagosi.ipa Payload
          ls -lh Halyagosi.ipa
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Halyagosi-IPA
          path: ${{ env.PROJECT_DIR }}/Halyagosi.ipa
